const { withAndroidManifest, AndroidConfig } = require("expo/config-plugins");

/**
 * Makes the camera actually reachable on Android 11+.
 *
 * Two separate things are missing without this, and each one on its own is
 * enough to make "Take photo" do nothing at all:
 *
 * 1. `android.permission.CAMERA`. The expo-image-picker plugin's
 *    `cameraPermission` option only writes the iOS usage description; it does
 *    not declare the Android permission.
 *
 * 2. A `<queries>` element for the capture intents. Since Android 11, package
 *    visibility is opt-in: an app that hasn't declared the intent it wants to
 *    resolve is told no camera app exists. `launchCameraAsync` then never
 *    starts an activity and its promise never settles — the button looks dead
 *    rather than failing, which is exactly how this presented.
 *
 * Kept as a local plugin because it belongs to the generated manifest, and
 * /android is regenerated by prebuild (never hand-edited).
 */
const CAPTURE_ACTIONS = [
  "android.media.action.IMAGE_CAPTURE",
  "android.media.action.VIDEO_CAPTURE",
];

module.exports = function withCameraCapture(config) {
  return withAndroidManifest(config, (mod) => {
    AndroidConfig.Permissions.addPermission(
      mod.modResults,
      "android.permission.CAMERA",
    );

    const manifest = mod.modResults.manifest;
    manifest.queries = manifest.queries ?? [];
    if (manifest.queries.length === 0) manifest.queries.push({});
    const queries = manifest.queries[0];
    queries.intent = queries.intent ?? [];

    for (const action of CAPTURE_ACTIONS) {
      const already = queries.intent.some(
        (entry) => entry.action?.[0]?.$?.["android:name"] === action,
      );
      if (already) continue;
      queries.intent.push({ action: [{ $: { "android:name": action } }] });
    }

    return mod;
  });
};
