// Let a LOCAL build talk to a LOCAL http API — loopback only, and only when
// asked for.
//
// THE TRAP THIS EXISTS TO CLOSE. Android blocks cleartext by default at
// targetSdk >= 28. React Native grants an exemption in
// `android/app/src/debug/AndroidManifest.xml`, so `expo run:android` works —
// but this repo's on-device verification path is a *debuggable release* build
// (`android/app/build.gradle`, release + `debuggable true`), because Metro
// cannot run on the dev laptop. That variant gets release's network policy, so
// every request to `http://127.0.0.1:8080` is refused inside the app, before a
// packet moves. React Native reports it as a bare `TypeError: Network request
// failed` and a release bundle has no console, so it is indistinguishable from
// a dead `adb reverse` or a stopped API — which is exactly how it burned an
// afternoon on 2026-08-30.
//
// WHY NOT `usesCleartextTraffic: true`. That is the one-line fix and it is the
// wrong one: it disables the guard for every host in every shipped build, to
// buy a developer convenience. This app's whole argument is that it does not
// leak where you have been. A network security config says the same thing about
// loopback and nothing else, so the guard stays on everywhere it can matter.
//
// WHY GATED. Same reasoning as `withSensorLogging.js`: config a user cannot
// reach should not be in a user's build at all, even when it is inert. Set
// `LOGJAM_LOCAL_API=1` at BUILD time — `scripts/build-local-apk.sh` does it for
// you. Deliberately not an `EXPO_PUBLIC_*` var: those are values the JS bundle
// reads, and this one decides what gets compiled into the manifest.
//
// 127.0.0.1 only, never 10.0.2.2. `adb reverse tcp:8080 tcp:8080` works on the
// emulator and on a physical device alike, so loopback is the one address that
// needs no per-target `.env` edit — and editing `.env` has its own trap (see
// the script, and mobile/CLAUDE.local.md).
const { AndroidConfig, withAndroidManifest, withDangerousMod } = require("expo/config-plugins");
const fs = require("fs");
const path = require("path");

const ENV_FLAG = "LOGJAM_LOCAL_API";
const CONFIG_RESOURCE = "network_security_config";

const NETWORK_SECURITY_CONFIG = `<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by plugins/withLocalApiCleartext.js — do not edit by hand.
     Present only in builds made with ${ENV_FLAG}=1. -->
<network-security-config>
    <!-- The local dev API and MiniStack, reached over \`adb reverse\`. Cleartext
         is permitted HERE and nowhere else; every other host keeps the platform
         default, which refuses it. Nothing remote can be loopback, so this is
         inert on a device that is not plugged into a dev machine. -->
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="false">127.0.0.1</domain>
        <domain includeSubdomains="false">localhost</domain>
    </domain-config>
</network-security-config>
`;

// BOTH directions are applied, and that is the point: `android/` is a generated
// directory that PERSISTS between builds, so a plugin that simply returns early
// when the flag is off leaves whatever the last flagged build wrote. That state
// is worse than either end — the manifest still points at `@xml/...` while the
// resource is gone, which is a missing-resource build failure at best and a
// stale exemption you did not ask for at worst. Off means actively removed.
module.exports = function withLocalApiCleartext(config) {
  const enabled = process.env[ENV_FLAG] === "1";

  // The resource lives next to the manifest that references it.
  config = withDangerousMod(config, [
    "android",
    (cfg) => {
      const xmlDir = path.join(cfg.modRequest.platformProjectRoot, "app/src/main/res/xml");
      const xmlPath = path.join(xmlDir, `${CONFIG_RESOURCE}.xml`);
      if (enabled) {
        fs.mkdirSync(xmlDir, { recursive: true });
        fs.writeFileSync(xmlPath, NETWORK_SECURITY_CONFIG, "utf8");
      } else {
        fs.rmSync(xmlPath, { force: true });
      }
      return cfg;
    },
  ]);

  return withAndroidManifest(config, (cfg) => {
    const application = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults);
    const attribute = "android:networkSecurityConfig";
    const ours = `@xml/${CONFIG_RESOURCE}`;
    if (enabled) {
      application.$[attribute] = ours;
    } else if (application.$[attribute] === ours) {
      // Only ever clear OUR value: another plugin may legitimately own this
      // attribute, and stomping it would be a security change made by accident.
      delete application.$[attribute];
    }
    return cfg;
  });
};
