const { withAndroidManifest, AndroidConfig } = require("expo/config-plugins");

/**
 * Manifest corrections for the media path.
 *
 * Two of them make the camera reachable on Android 11+, and each one on its own
 * is enough to make "Take photo" do nothing at all. The third takes away a
 * permission a dependency asks for and this app has no use for — see
 * BLOCKED_PERMISSIONS.
 *
 * 1. `android.permission.CAMERA`. The expo-image-picker plugin's
 *    `cameraPermission` option only writes the iOS usage description; it does
 *    not declare the Android permission.
 *
 * 2. A `<queries>` element for the capture intents. Since Android 11, package
 *    visibility is opt-in: an app that hasn't declared the intent it wants to
 *    resolve is told no camera app exists. `launchCameraAsync` then never
 *    starts an activity and its promise never settles — the button looks dead
 *    rather than failing, which is exactly how this presented.
 *
 * Kept as a local plugin because it belongs to the generated manifest, and
 * /android is regenerated by prebuild (never hand-edited).
 */
const CAPTURE_ACTIONS = [
  "android.media.action.IMAGE_CAPTURE",
  "android.media.action.VIDEO_CAPTURE",
];

/**
 * Permissions declared by a dependency that this app must not ask for.
 *
 * `expo-media-library`'s config plugin declares the full READ_MEDIA_* set
 * because the library can read audio, images and video. Logjam only ever WRITES
 * — one copy of a photo or video the user just shot, when they have turned that
 * on (`media/galleryPreference.ts`) — and it has no audio feature at all. An
 * app that asks for the phone's music library in its permission list is asking
 * for something it cannot explain, which is exactly the posture the privacy
 * rules exist to avoid (root CLAUDE.md).
 *
 * READ_MEDIA_IMAGES / READ_MEDIA_VIDEO stay: `expo-image-picker` genuinely
 * needs them for "Attach from library".
 */
const BLOCKED_PERMISSIONS = ["android.permission.READ_MEDIA_AUDIO"];

module.exports = function withCameraCapture(config) {
  // `withBlockedPermissions` rather than filtering the array ourselves: plugin
  // mods run in a composed order we do not control, so a filter here can run
  // BEFORE the plugin that adds the entry (it does). Blocking marks it
  // `tools:node="remove"`, which the manifest merger honours whenever the
  // declaration is added.
  const blocked = AndroidConfig.Permissions.withBlockedPermissions(
    config,
    BLOCKED_PERMISSIONS,
  );
  return withAndroidManifest(blocked, (mod) => {
    AndroidConfig.Permissions.addPermission(
      mod.modResults,
      "android.permission.CAMERA",
    );

    const manifest = mod.modResults.manifest;
    manifest.queries = manifest.queries ?? [];
    if (manifest.queries.length === 0) manifest.queries.push({});
    const queries = manifest.queries[0];
    queries.intent = queries.intent ?? [];

    for (const action of CAPTURE_ACTIONS) {
      const already = queries.intent.some(
        (entry) => entry.action?.[0]?.$?.["android:name"] === action,
      );
      if (already) continue;
      queries.intent.push({ action: [{ $: { "android:name": action } }] });
    }

    return mod;
  });
};
