// Make the LOCAL field-test APK both debuggable (so `run-as` can read its
// files) AND release-shaped for expo-updates. The two fight, and this exists
// to hold them apart.
//
// THE BUG. `android/app/build.gradle` sets `buildTypes.release { debuggable
// true }` so a release-shaped APK (embedded bundle, no Metro dependency in a
// canyon) can still be read with `run-as`. But Android Gradle Plugin ties
// `BuildConfig.DEBUG` to the `debuggable` flag, not to the build-type NAME —
// so a "release" build with `debuggable true` gets `BuildConfig.DEBUG = true`.
// The app's `getUseDeveloperSupport()` returns `BuildConfig.DEBUG`, so
// expo-updates sees `useDeveloperSupport = true` and initialises as a
// dev-client build (`UpdatesDevLauncherController`) instead of running its real
// startup: it never loads the embedded update, `ExpoUpdates.localAssets` stays
// empty, and every `require()`d asset resolves to an empty URI. On a fresh
// install the map draws no glyph pack, no labels, and no location marker —
// line and fill layers look fine, so it presents as a styling bug in whatever
// you last touched. Found 2026-09-01; full writeup in
// private/todo/local-release-asset.resolution.md.
//
// THE FIX. Force `BuildConfig.DEBUG` back to false in the release build type,
// next to `debuggable true`. The APK stays debuggable (the manifest
// `android:debuggable="true"` comes from the `debuggable` flag, untouched), so
// `run-as` keeps working; but `getUseDeveloperSupport()` returns false again,
// so expo-updates runs its real startup and `localAssets` is populated.
//
// WHY GATED. Same reasoning as `withLocalApiCleartext.js` and
// `withSensorLogging.js`: a build a user cannot reach should not carry
// debuggable/DEBUG-false config at all. `LOGJAM_LOCAL_API=1` at BUILD time —
// `scripts/build-local-apk.sh` sets it. Deliberately not an `EXPO_PUBLIC_*`
// var: those are read by the JS bundle, and this decides what compiles into the
// manifest and BuildConfig.
//
// BOTH DIRECTIONS APPLY, and that is the point. `android/` persists between
// builds, so a plugin that only adds when the flag is on would leave the lines
// behind in a later unflagged build. Off means actively removed.
const { withDangerousMod } = require("expo/config-plugins");
const fs = require("fs");
const path = require("path");

const ENV_FLAG = "LOGJAM_LOCAL_API";
const MARKER = "withLocalDebuggableRelease";

const START = `            // __${MARKER}_START__ (generated by plugins/${MARKER}.js; do not edit)`;
const LINES = [
  START,
  `            debuggable true`,
  `            buildConfigField "boolean", "DEBUG", "false"`,
];

module.exports = function withLocalDebuggableRelease(config) {
  const enabled = process.env[ENV_FLAG] === "1";

  return withDangerousMod(config, [
    "android",
    (cfg) => {
      const buildGradle = path.join(cfg.modRequest.platformProjectRoot, "app/build.gradle");
      if (!fs.existsSync(buildGradle)) {
        return cfg; // no android project yet (e.g. `expo config` without prebuild)
      }
      let text = fs.readFileSync(buildGradle, "utf8");

      // Strip whatever this plugin (or an earlier build) wrote, in whole lines.
      const lines = text.split("\n");
      const filtered = [];
      let dropping = false;
      for (const line of lines) {
        if (line.includes(`__${MARKER}_START__`)) {
          dropping = true;
          continue;
        }
        if (dropping) {
          if (line.trim() === "debuggable true" || line.includes('"DEBUG"')) {
            continue;
          }
          dropping = false; // only the two following lines are ours
        }
        filtered.push(line);
      }
      text = filtered.join("\n");

      if (enabled) {
        // Insert inside the release build type, right after its opening brace.
        const releaseRe = /(\n[ \t]*release[ \t]*\{)/;
        if (releaseRe.test(text)) {
          text = text.replace(releaseRe, `$1\n${LINES.join("\n")}`);
        }
      }

      fs.writeFileSync(buildGradle, text, "utf8");
      return cfg;
    },
  ]);
};
