.PHONY: setup dev dev-snapshot dev-cognito reset seed snapshot logs down help shared build-workers _ministack-tf geo-pdf-run install format format-check lint typecheck verify

# Load .env.local if present (provides AUTH_MODE, FAKE_USER_SUB, Cognito vars etc.)
# Generated by Terraform (see _ministack-tf); regenerated on dev/reset.
-include .env.local
export

LOCAL_TF := infra/terraform/envs/local
PACKAGES := . shared api frontend mobile infra/lambda/cognito-email-sender


# ── Primary targets ────────────────────────────────────────────────────────────

## Start full local env (fake auth, seeded fixtures)
dev: shared build-workers
	@echo "Starting infra..."
	docker compose up -d postgres ministack
	@$(MAKE) _wait-healthy
	@$(MAKE) _ministack-tf
	@echo "Generating Prisma client..."
	cd api && npx prisma generate
	@echo "Running migrations..."
	cd api && DB_HOST=localhost DB_PORT=5432 DB_NAME=logjam DB_USER=logjam DB_PASSWORD=logjam npx prisma migrate deploy
	@echo "Seeding fixtures..."
	cd api && DB_HOST=localhost DB_PORT=5432 DB_NAME=logjam DB_USER=logjam DB_PASSWORD=logjam npx prisma db seed
	@echo ""
	@echo "  Infra ready. Start app servers in separate terminals:"
	@echo "    Terminal 1: cd api  && npm run dev"
	@echo "    Terminal 2: cd frontend && npm run dev"
	@echo ""
	@echo "  Logged in as: alice (FAKE_USER_SUB=fake-alice-sub)"
	@echo "  Switch user:  FAKE_USER_SUB=fake-bob-sub  (restart api)"

## Start local env with sanitized prod snapshot (real Cognito auth)
dev-snapshot:
	@if [ ! -f snapshots/latest.sql ]; then \
		echo "ERROR: snapshots/latest.sql not found. Run 'make snapshot' first."; \
		exit 1; \
	fi
	@echo "Wiping volumes and restoring snapshot..."
	docker compose down -v
	docker compose up -d postgres ministack
	@$(MAKE) _wait-healthy
	@rm -f $(LOCAL_TF)/terraform.tfstate $(LOCAL_TF)/terraform.tfstate.backup
	@$(MAKE) _ministack-tf
	@echo "Restoring snapshot into DB..."
	docker compose exec -T postgres psql -U logjam logjam < snapshots/latest.sql
	@echo "Applying any migrations not present in snapshot..."
	cd api && DB_HOST=localhost DB_PORT=5432 DB_NAME=logjam DB_USER=logjam DB_PASSWORD=logjam npx prisma migrate deploy
	@echo ""
	@echo "  Snapshot loaded. Start app servers:"
	@echo "    Terminal 1: AUTH_MODE=cognito cd api  && npm run dev"
	@echo "    Terminal 2: cd frontend && VITE_AUTH_MODE=cognito npm run dev"

## Reset: wipe DB + MiniStack volumes, restart, re-seed
reset: shared build-workers
	docker compose down -v
	docker compose up -d postgres ministack
	@$(MAKE) _wait-healthy
	@rm -f $(LOCAL_TF)/terraform.tfstate $(LOCAL_TF)/terraform.tfstate.backup
	@$(MAKE) _ministack-tf
	cd api && npx prisma generate
	cd api && DB_HOST=localhost DB_PORT=5432 DB_NAME=logjam DB_USER=logjam DB_PASSWORD=logjam npx prisma migrate deploy
	cd api && DB_HOST=localhost DB_PORT=5432 DB_NAME=logjam DB_USER=logjam DB_PASSWORD=logjam npx prisma db seed
	@echo "Reset complete."

## Build the shared package — api + frontend import @logjam/shared via file:../shared
## and read from shared/dist/, so dist must exist before either app starts.
shared:
	@echo "Building shared package..."
	cd shared && npm run build

## Build the worker Docker images that MiniStack RunTask launches locally. The
## local ECS task defs (infra/terraform/envs/local/ecs.tf) reference these tags;
## rebuild after changing worker code (local analogue of CI's ECR push). Docker
## layer caching keeps this fast when nothing changed.
build-workers:
	@echo "Building worker images (logjam-topo-worker, logjam-api)..."
	docker build -t logjam-topo-worker:latest topo
	docker build -t logjam-api:latest -f api/Dockerfile .

## Re-run seed without wiping volumes
seed:
	cd api && DB_HOST=localhost DB_PORT=5432 DB_NAME=logjam DB_USER=logjam DB_PASSWORD=logjam npx prisma db seed

## Manual fallback: run the GeoPDF worker in-process for one job. Normally
## unnecessary — submitted GeoPDF jobs auto-launch via MiniStack RunTask. Use
## this to debug the worker without a container. Usage:
##   make geo-pdf-run JOB=<geoPdfJobId>
## Other config (S3/AWS/MiniStack) comes from .env.local, loaded above.
geo-pdf-run:
	@if [ -z "$(JOB)" ]; then echo "Usage: make geo-pdf-run JOB=<geoPdfJobId>"; exit 1; fi
	cd api && DB_HOST=localhost DB_PORT=5432 DB_NAME=logjam DB_USER=logjam DB_PASSWORD=logjam \
		GEO_PDF_JOB_ID=$(JOB) npx ts-node src/worker/geoPdfWorker.ts

## Dump + sanitize prod DB into snapshots/latest.sql
## Requires DB_HOST_PROD, DB_NAME_PROD, DB_USER_PROD and DB_PASSWORD_PROD env
## vars pointing at the prod RDS instance (DB_PORT_PROD optional, default 5432).
## Password lives in Secrets Manager — fetch it manually before running this.
snapshot:
	@if [ -z "$$DB_HOST_PROD" ] || [ -z "$$DB_NAME_PROD" ] || [ -z "$$DB_USER_PROD" ] || [ -z "$$DB_PASSWORD_PROD" ]; then \
		echo "ERROR: DB_HOST_PROD, DB_NAME_PROD, DB_USER_PROD and DB_PASSWORD_PROD must all be set."; \
		exit 1; \
	fi
	mkdir -p snapshots
	bash scripts/snapshot.sh

## Tail API logs (if API is running as a background process — otherwise use the terminal)
logs:
	docker compose logs -f

## Stop infra containers
down:
	docker compose down

## setup: One command from a fresh clone to make dev (tools, dependencies, shared build, Prisma)
setup:
	@if command -v mise >/dev/null 2>&1; then \
		echo "Installing mise tools..."; \
		mise install; \
	else \
		echo "mise is not installed; skipping tool installation."; \
		echo "Tools specified in mise.toml:"; \
		sed -n '/^\[tools\]/,/^\[/p' mise.toml | grep -v '^\[' | grep -v '^[[:space:]]*$$' | sed 's/^/  /'; \
	fi
	@for pkg in $(PACKAGES); do \
		echo "Installing dependencies in $$pkg..."; \
		(cd $$pkg && npm ci) || exit 1; \
	done
	@$(MAKE) shared
	@echo "Generating Prisma client..."
	cd api && npx prisma generate
	@if [ -f topo/requirements-test.txt ]; then \
		echo "Installing topo test requirements..."; \
		pip install -r topo/requirements-test.txt; \
	fi

## Install dependencies across all packages
install:
	@for pkg in $(PACKAGES); do \
		if [ ! -d $$pkg/node_modules ]; then \
			(cd $$pkg && npm ci) || exit 1; \
		fi; \
	done

## Format all code (Biome + Ruff)
format:
	npm run format

## Check code formatting (Biome + Ruff)
format-check:
	npm run format:check

## Lint all packages (ESLint + Ruff)
lint:
	npm run lint

## Typecheck all packages
typecheck:
	npm run typecheck

## Verify codebase (format check + lint + typecheck)
verify: install
	npm run verify

## Print available targets
help:
	@grep -E '^## ' Makefile | sed 's/## //'

# ── Internal helpers ───────────────────────────────────────────────────────────

## Provision MiniStack S3 buckets + ECS cluster/task defs + (re)generate
## .env.local via Terraform. Walled off to MiniStack (dummy creds + :4566
## endpoint) — never touches AWS.
_ministack-tf:
	@echo "Provisioning MiniStack S3 + ECS (Terraform)..."
	@cd $(LOCAL_TF) && terraform init -input=false -upgrade=false >/dev/null
	@cd $(LOCAL_TF) && terraform apply -input=false -auto-approve

_wait-healthy:
	@echo "Waiting for Postgres..."
	@until docker compose exec -T postgres pg_isready -U logjam > /dev/null 2>&1; do sleep 1; done
	@echo "Waiting for MiniStack..."
	@until curl -sf http://localhost:4566/_localstack/health | grep -q '"s3": "available"' > /dev/null 2>&1; do sleep 2; done
	@echo "Infra healthy."
