.PHONY: dev dev-snapshot dev-cognito reset seed snapshot logs down help shared _localstack-tf

# Load .env.local if present (provides AUTH_MODE, FAKE_USER_SUB, Cognito vars etc.)
# Generated by Terraform (see _localstack-tf); regenerated on dev/reset.
-include .env.local
export

LOCAL_TF := infra/terraform/envs/local

# ── Primary targets ────────────────────────────────────────────────────────────

## Start full local env (fake auth, seeded fixtures)
dev: shared
	@echo "Starting infra..."
	docker compose up -d postgres localstack
	@$(MAKE) _wait-healthy
	@$(MAKE) _localstack-tf
	@echo "Running migrations..."
	cd api && DB_HOST=localhost DB_PORT=5432 DB_NAME=logjam DB_USER=logjam DB_PASSWORD=logjam npx prisma migrate deploy
	@echo "Seeding fixtures..."
	cd api && DB_HOST=localhost DB_PORT=5432 DB_NAME=logjam DB_USER=logjam DB_PASSWORD=logjam npx prisma db seed
	@echo ""
	@echo "  Infra ready. Start app servers in separate terminals:"
	@echo "    Terminal 1: cd api  && npm run dev"
	@echo "    Terminal 2: cd frontend && npm run dev"
	@echo ""
	@echo "  Logged in as: alice (FAKE_USER_SUB=fake-alice-sub)"
	@echo "  Switch user:  FAKE_USER_SUB=fake-bob-sub  (restart api)"

## Start local env with sanitized prod snapshot (real Cognito auth)
dev-snapshot:
	@if [ ! -f snapshots/latest.sql ]; then \
		echo "ERROR: snapshots/latest.sql not found. Run 'make snapshot' first."; \
		exit 1; \
	fi
	@echo "Wiping volumes and restoring snapshot..."
	docker compose down -v
	docker compose up -d postgres localstack
	@$(MAKE) _wait-healthy
	@rm -f $(LOCAL_TF)/terraform.tfstate $(LOCAL_TF)/terraform.tfstate.backup
	@$(MAKE) _localstack-tf
	@echo "Restoring snapshot into DB..."
	docker compose exec -T postgres psql -U logjam logjam < snapshots/latest.sql
	@echo "Applying any migrations not present in snapshot..."
	cd api && DB_HOST=localhost DB_PORT=5432 DB_NAME=logjam DB_USER=logjam DB_PASSWORD=logjam npx prisma migrate deploy
	@echo ""
	@echo "  Snapshot loaded. Start app servers:"
	@echo "    Terminal 1: AUTH_MODE=cognito cd api  && npm run dev"
	@echo "    Terminal 2: cd frontend && VITE_AUTH_MODE=cognito npm run dev"

## Reset: wipe DB + LocalStack volumes, restart, re-seed
reset: shared
	docker compose down -v
	docker compose up -d postgres localstack
	@$(MAKE) _wait-healthy
	@rm -f $(LOCAL_TF)/terraform.tfstate $(LOCAL_TF)/terraform.tfstate.backup
	@$(MAKE) _localstack-tf
	cd api && DB_HOST=localhost DB_PORT=5432 DB_NAME=logjam DB_USER=logjam DB_PASSWORD=logjam npx prisma migrate deploy
	cd api && DB_HOST=localhost DB_PORT=5432 DB_NAME=logjam DB_USER=logjam DB_PASSWORD=logjam npx prisma db seed
	@echo "Reset complete."

## Build the shared package — api + frontend import @logjam/shared via file:../shared
## and read from shared/dist/, so dist must exist before either app starts.
shared:
	@echo "Building shared package..."
	cd shared && npm run build

## Re-run seed without wiping volumes
seed:
	cd api && DB_HOST=localhost DB_PORT=5432 DB_NAME=logjam DB_USER=logjam DB_PASSWORD=logjam npx prisma db seed

## Dump + sanitize prod DB into snapshots/latest.sql
## Requires DB_HOST_PROD, DB_NAME_PROD, DB_USER_PROD and DB_PASSWORD_PROD env
## vars pointing at the prod RDS instance (DB_PORT_PROD optional, default 5432).
## Password lives in Secrets Manager — fetch it manually before running this.
snapshot:
	@if [ -z "$$DB_HOST_PROD" ] || [ -z "$$DB_NAME_PROD" ] || [ -z "$$DB_USER_PROD" ] || [ -z "$$DB_PASSWORD_PROD" ]; then \
		echo "ERROR: DB_HOST_PROD, DB_NAME_PROD, DB_USER_PROD and DB_PASSWORD_PROD must all be set."; \
		exit 1; \
	fi
	mkdir -p snapshots
	bash scripts/snapshot.sh

## Tail API logs (if API is running as a background process — otherwise use the terminal)
logs:
	docker compose logs -f

## Stop infra containers
down:
	docker compose down

## Print available targets
help:
	@grep -E '^## ' Makefile | sed 's/## //'

# ── Internal helpers ───────────────────────────────────────────────────────────

## Provision LocalStack S3 buckets + (re)generate .env.local via Terraform.
## Walled off to LocalStack (dummy creds + :4566 endpoint) — never touches AWS.
_localstack-tf:
	@echo "Provisioning LocalStack S3 (Terraform)..."
	@cd $(LOCAL_TF) && terraform init -input=false -upgrade=false >/dev/null
	@cd $(LOCAL_TF) && terraform apply -input=false -auto-approve

_wait-healthy:
	@echo "Waiting for Postgres..."
	@until docker compose exec -T postgres pg_isready -U logjam > /dev/null 2>&1; do sleep 1; done
	@echo "Waiting for LocalStack..."
	@until curl -sf http://localhost:4566/_localstack/health | grep -q running > /dev/null 2>&1; do sleep 2; done
	@echo "Infra healthy."
