plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.logjamdownloadservice'
version = '0.1.0'

android {
  namespace "expo.modules.logjamdownloadservice"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }
  lintOptions {
    abortOnError false
  }
}
