#!/usr/bin/env bash
# Vendors the Protomaps glyph/sprite assets into the mobile app bundle
# (stage 4a §8.3: offline regions must render labels with zero network).
#
# Produces:
#   mobile/assets/basemap/basemap-assets.zip   — fonts + sprites, extracted to
#                                                <documentDirectory>/basemap-assets/
#                                                on first launch (basemapAssets.ts)
#   mobile/src/map/basemap/basemapAssetsVersion.ts — generated pin constant; the
#                                                installer uses it as the
#                                                extraction version marker
#
# Pinned to a protomaps/basemaps-assets commit. Refresh deliberately, together
# with a style-package bump (scripts/basemap/generate-style.mjs) — the flavors'
# font references and the sprite sheet must stay in lockstep with the style.
#
# Assets are OFL (fonts) / permissively licensed (sprites); OFL.txt ships in
# the zip. ODbL attribution is handled in-app, not here.
set -euo pipefail

COMMIT=028c18f713baecad011301ff7a69acc39bcc2ae7
# GitHub tarballs have been byte-stable in practice but are not contractually
# guaranteed; a mismatch means STOP AND INVESTIGATE (compare file contents),
# not silently re-pin.
TARBALL_SHA256=57e40e8c512bd8042d0a3a251f19d0d1c8523ad963c666c3c6643bada4dc92d0

# Font stacks the generated layer JSONs may reference. Verified against the
# committed JSONs below — the build fails if a referenced stack is missing.
FONT_STACKS=(
  "Noto Sans Regular"
  "Noto Sans Medium"
  "Noto Sans Italic"
  "Noto Sans Devanagari Regular v1"
)
SPRITE_FLAVORS=(light dark)

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
OUT_DIR="$REPO_ROOT/mobile/assets/basemap"
VERSION_TS="$REPO_ROOT/mobile/src/map/basemap/basemapAssetsVersion.ts"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

echo "Downloading protomaps/basemaps-assets @ $COMMIT ..."
curl -fsSL -o "$WORK/assets.tar.gz" \
  "https://github.com/protomaps/basemaps-assets/archive/$COMMIT.tar.gz"
echo "$TARBALL_SHA256  $WORK/assets.tar.gz" | sha256sum -c - >/dev/null

tar -xzf "$WORK/assets.tar.gz" -C "$WORK"
SRC="$WORK/basemaps-assets-$COMMIT"

# Stage exactly what the app needs.
STAGE="$WORK/stage"
mkdir -p "$STAGE/fonts" "$STAGE/sprites/v4"
for stack in "${FONT_STACKS[@]}"; do
  [ -d "$SRC/fonts/$stack" ] || { echo "ERROR: font stack '$stack' missing from assets repo" >&2; exit 1; }
  cp -r "$SRC/fonts/$stack" "$STAGE/fonts/"
done
cp "$SRC/fonts/OFL.txt" "$STAGE/fonts/"
for flavor in "${SPRITE_FLAVORS[@]}"; do
  for f in "$flavor.json" "$flavor.png" "$flavor@2x.json" "$flavor@2x.png"; do
    [ -f "$SRC/sprites/v4/$f" ] || { echo "ERROR: sprite file '$f' missing from assets repo" >&2; exit 1; }
    cp "$SRC/sprites/v4/$f" "$STAGE/sprites/v4/"
  done
done

# Assert bundled stacks ⊇ stacks referenced by the committed layer JSONs
# (fail loudly — a missing stack means blank labels offline).
node - "$REPO_ROOT" "${FONT_STACKS[@]}" <<'EOF'
const fs = require("fs");
const path = require("path");
const [repoRoot, ...bundled] = process.argv.slice(2);
const referenced = new Set();
for (const flavor of ["light", "dark"]) {
  const json = fs.readFileSync(
    path.join(repoRoot, `mobile/src/map/basemap/protomapsLayers.${flavor}.json`),
    "utf8"
  );
  for (const m of json.matchAll(/"(Noto [^"]+)"/g)) referenced.add(m[1]);
}
const missing = [...referenced].filter((s) => !bundled.includes(s));
if (missing.length) {
  console.error(`ERROR: layer JSONs reference unbundled font stacks: ${missing.join(", ")}`);
  process.exit(1);
}
console.log(`Font stacks referenced by styles: ${[...referenced].join(", ")} — all bundled.`);
EOF

mkdir -p "$OUT_DIR"
rm -f "$OUT_DIR/basemap-assets.zip"
# -X strips platform extra fields for reproducibility; store paths relative to stage.
(cd "$STAGE" && zip -q -r -X "$OUT_DIR/basemap-assets.zip" fonts sprites)

cat > "$VERSION_TS" <<EOF
// Generated by scripts/basemap/fetch-assets.sh — do not edit by hand.
// Pin of protomaps/basemaps-assets vendored into assets/basemap/basemap-assets.zip.
// The installer (basemapAssets.ts) re-extracts when this value changes.
export const BASEMAP_ASSETS_COMMIT = "$COMMIT";
EOF

echo "Wrote $OUT_DIR/basemap-assets.zip ($(du -h "$OUT_DIR/basemap-assets.zip" | cut -f1))"
echo "Wrote $VERSION_TS"
