// Generated by scripts/basemap/fetch-assets.sh — do not edit by hand.
// Pin of protomaps/basemaps-assets vendored into assets/basemap/basemap-assets.zip.
// The installer (basemapAssets.ts) re-extracts when this value changes.
export const BASEMAP_ASSETS_COMMIT = "028c18f713baecad011301ff7a69acc39bcc2ae7";
