// Typed accessor over the committed Protomaps layer JSONs (generated by
// scripts/basemap/generate-style.mjs — regenerate there, never hand-edit the
// JSONs). Each entry is MLRN-ready: paint+layout already merged into a
// camelCase `style` object; filter/zooms/source-layer ride as component props.
import lightLayers from "./protomapsLayers.light.json";
import darkLayers from "./protomapsLayers.dark.json";

export type ProtomapsFlavor = "light" | "dark";

export interface ProtomapsLayerDef {
  id: string;
  type: "background" | "fill" | "line" | "symbol";
  sourceLayer?: string;
  filter?: unknown[];
  minzoom?: number;
  maxzoom?: number;
  style: Record<string, unknown>;
}

interface GeneratedFile {
  _meta: { package: string; flavor: string; fontStacks: string[] };
  layers: ProtomapsLayerDef[];
}

const FILES: Record<ProtomapsFlavor, GeneratedFile> = {
  light: lightLayers as unknown as GeneratedFile,
  dark: darkLayers as unknown as GeneratedFile,
};

export function protomapsLayerDefs(flavor: ProtomapsFlavor): ProtomapsLayerDef[] {
  return FILES[flavor].layers;
}
