// GENERATED by scripts/generate-route-arrow-sdf.mjs — do not edit by hand.
// Run that script to change the arrowhead's shape; `routeArrowStyle.ts` scales
// it, so size is not a reason to regenerate. Guarded by routeArrowStyle.test.ts.
//
// 64x48 SDF, 26x26 arrowhead centred in it, distance in the alpha
// channel with the shape edge at alpha 191 and a 8px spread.
export const ROUTE_ARROW_SDF_URI =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAAAwCAYAAAChS3wfAAABTElEQVR42u3asU3DQBjFcdcnodCnorNoQmUxQdpQMEHoI+gjMQFiARYIDS0TpKViAgZATPDnTnotCGI78ee8SJ8UWbri/Wwn991dBVTHXJUBDGAAA3RQCZio0jEBlLBToAZmqlrXTsYOUMKfAQ0wBxaq8v0SOI8A0WbwVOFL6CWwUt0A11Eg2tz9WiFL+HUO+KC6B+6iQOw6cKL3faG7XoJvcshn4CkSxK4DT4EL4Aq4zSCPGeQlh9zmkK+RILoGeAPeI0H0AfCZQ35EgegLoHy+IkD0CUAEiH0ADBpinwCDhDgEwKAgDgnQFUSKDtAGolFDlsYA8F+IpabijZ6E0QD8FWIthLkaszQ2gN8gNkJY6SmYqUEzgF8B/wj6b9ATIU+F3Qy5HfaCiJfEvCjqZXFvjHhrzJuj3h73AQkfkfEhKR+TM4ABDGCAH+sb7+P0fNuGERcAAAAASUVORK5CYII=";
