// The direction arrows drawn along a route line, as a pure style builder.
//
// Split out of `RouteDraftLayer` (which pulls in React Native and MLRN) so the
// centring invariant below can be asserted in a plain node test — the same
// split `topoVectorLayers.ts` uses.
import type {
  FilterSpecification,
  SymbolLayerStyle,
} from "@maplibre/maplibre-react-native";

import { theme } from "../theme";

/** Below this a route is a few pixels of line and arrows on it are just noise. */
export const ROUTE_ARROW_MIN_ZOOM = 12;

/**
 * Style-image name. The image itself is registered ONCE, by `RouteArrowImage`
 * in `MapScreen` — a style image is global to the map, so registering it per
 * layer would have two components racing to define the same name.
 */
export const ROUTE_ARROW_IMAGE = "route-arrow";

/**
 * Scales the 64x48 source image, so the 26px arrowhead inside it draws about
 * 12dp long on a 3dp line. Tune here, not by regenerating the image: an SDF is
 * resolution-independent, which is half of why it is one.
 */
const ARROW_ICON_SIZE = 0.45;

/**
 * Which way the line runs, as arrows along it — MapLibre spaces and rotates
 * them itself, so they re-space as you zoom and cost no React views (the
 * markers this replaced were re-created on every drag frame, which is what made
 * dragging an anchor stutter).
 *
 * A STYLE, not a component of ours, and three things here are load-bearing:
 *
 * - The layer has to be a DIRECT child of its `GeoJSONSource`. MLRN injects
 *   `source` onto the source's immediate children with `cloneElement`, so a
 *   layer wrapped in a component of ours never learns which source it belongs
 *   to, falls back to the default source id and draws nothing.
 * - The image must be registered as **SDF**. `iconColor` and `iconHaloColor`
 *   are ignored for an ordinary bitmap, so a non-SDF arrow would be one fixed
 *   colour for every route — the per-feature `["get", "routeColor"]` expression
 *   below only works because the image is a distance field the GPU tints.
 * - `iconAllowOverlap`/`iconIgnorePlacement` so an arrow never loses a
 *   placement contest with a street label, and `iconKeepUpright` off (the
 *   default, stated because it matters) because an arrow that flips itself to
 *   stay readable is then pointing the wrong way.
 *
 * THE ARROWHEAD IS AN IMAGE BECAUSE THE FONT HAS NO ARROWHEAD. This was a text
 * layer until 2026-08-30, first `›` and then `→`, and both were
 * compromises with the bundled Noto Sans pack: it ships no filled triangle at
 * all (one glyph in the geometric block, U+25CC; only U+2190-2199 in the arrows
 * block, every one stemmed). A stem drawn along a line is a second line, so the
 * arrow read as a bulge in the route rather than a mark on it, and sizing it up
 * to be legible thickened the stem past the line itself.
 * `assets/route-arrow-sdf.png` is generated by
 * `scripts/generate-route-arrow-sdf.mjs`; the centring rule that applied to the
 * glyphs applies to it too, and is what its test asserts.
 */
export function routeArrowStyle(
  color: SymbolLayerStyle["iconColor"],
  spacing = 90,
): SymbolLayerStyle {
  return {
    symbolPlacement: "line",
    symbolSpacing: spacing,
    iconImage: ROUTE_ARROW_IMAGE,
    iconSize: ARROW_ICON_SIZE,
    iconColor: color,
    iconHaloColor: theme.primary,
    iconHaloWidth: 1,
    iconAllowOverlap: true,
    iconIgnorePlacement: true,
    iconKeepUpright: false,
    iconRotationAlignment: "map",
    iconPitchAlignment: "map",
  };
}

/**
 * Marks the per-segment features the arrow layer draws on, so the line layers
 * sharing the source can filter them back out.
 */
export const ARROW_FEATURE_KIND = "arrow";

/** Draws arrows; skips the segment features. */
export const ARROW_LAYER_FILTER: FilterSpecification = [
  "==",
  ["get", "kind"],
  ARROW_FEATURE_KIND,
];

/** Draws the route itself; skips the segment features. */
export const ROUTE_LAYER_FILTER: FilterSpecification = [
  "!=",
  ["get", "kind"],
  ARROW_FEATURE_KIND,
];

/**
 * ONE FEATURE PER SEGMENT, drawn by the arrow layer only — the route itself
 * stays a single LineString for the line layers, because a line split into
 * segments joins them with two round caps instead of one `lineJoin`, and on a
 * tight corner that reads as a notch.
 *
 * This is what keeps arrows OFF the anchor handles. MapLibre places
 * line symbols starting half a `symbolSpacing` into each line and every spacing
 * after that, so a per-segment line puts the first arrow ~45px past the anchor
 * it starts from, and a segment shorter than the spacing gets a single arrow at
 * its midpoint — the furthest point from both of its anchors. Doing it in
 * SCREEN space this way is why it holds at every zoom; trimming the geometry by
 * a ground distance instead would be a gap that grows as you zoom in and
 * vanishes as you zoom out, because the handle is a fixed 7dp either way.
 *
 * It also stops an arrow straddling a corner, where its rotation would split
 * the difference between two segments and point at neither.
 *
 * The cost is roughly double the coordinates for a route (a shared pair per
 * segment rather than one run), which is why the segments carry only the
 * properties the arrow layer's own paint expressions read.
 */
export function arrowSegmentFeatures<P extends Record<string, unknown>>(
  points: readonly (readonly number[])[],
  properties: P,
): GeoJSON.Feature<GeoJSON.LineString, P & { kind: string }>[] {
  const features: GeoJSON.Feature<GeoJSON.LineString, P & { kind: string }>[] = [];
  for (let i = 1; i < points.length; i++) {
    features.push({
      type: "Feature",
      geometry: {
        type: "LineString",
        coordinates: [[...points[i - 1]], [...points[i]]],
      },
      properties: { ...properties, kind: ARROW_FEATURE_KIND },
    });
  }
  return features;
}
