import {
  Activity,
  AlignLeft,
  Archive,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  Bell,
  BookOpen,
  Calendar,
  Camera,
  ChartColumn,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleCheck,
  CircleHelp,
  CircleUser,
  Clock,
  Cloud,
  CloudDownload,
  CloudOff,
  CloudUpload,
  Compass,
  Copy,
  CornerUpLeft,
  Cpu,
  Download,
  Ellipsis,
  EllipsisVertical,
  ExternalLink,
  Eye,
  EyeOff,
  FilePlus,
  FileText,
  Flag,
  Folder,
  GitCommit,
  GitMerge,
  GripVertical,
  HardDrive,
  Image,
  ImageOff,
  Info,
  Layers,
  LayoutTemplate,
  Link,
  Link2Off,
  ListChecks,
  Loader,
  Locate,
  LocateFixed,
  Lock,
  LogOut,
  Mail,
  Map,
  MapPin,
  MapPinPlus,
  Minus,
  Mountain,
  Navigation,
  Palette,
  Paperclip,
  Pause,
  PenTool,
  Pencil,
  Play,
  Plus,
  RefreshCw,
  Repeat,
  RotateCcw,
  Route,
  Ruler,
  RulerDimensionLine,
  Scan,
  Search,
  Send,
  Settings,
  Share,
  Share2,
  SlidersVertical,
  Smartphone,
  SquareCheck,
  SquareDashed,
  Star,
  Tag,
  Trash2,
  TrendingUp,
  TriangleAlert,
  Type,
  Upload,
  UserCheck,
  UserMinus,
  UserPlus,
  UserX,
  Users,
  Video,
  X,
  ZoomIn,
  ZoomOut,
  createLucideIcon,
  type LucideIcon,
} from "lucide-react";
import type { IconIdea } from "@logjam/shared";
import classes from "./Icon.module.css";

/**
 * The web half of the icon registry (`shared/src/icons.ts`): each idea's Lucide
 * component. Written as imports rather than looked up by name so the bundle
 * keeps only the glyphs listed here. `icons.test.ts` fails when a component
 * here is not the one the registry's `web` value names, or an idea is missing.
 *
 * This file and `placeTypeIcon.tsx` are the only places that import Lucide
 * (an ESLint rule holds the line).
 */
export const WEB_ICONS = {
  add: Plus,
  addPlace: MapPinPlus,
  remove: Minus,
  close: X,
  back: ArrowLeft,
  forward: ArrowRight,
  done: Check,
  edit: Pencil,
  delete: Trash2,
  undo: CornerUpLeft,
  search: Search,
  filter: SlidersVertical,
  selectAll: SquareCheck,
  multiSelect: ListChecks,
  copy: Copy,
  moveCopy: Archive,
  send: Send,
  shareFriend: Share2,
  unshare: UserMinus,
  export: Share,
  download: Download,
  saveOffline: CloudDownload,
  upload: Upload,
  link: Link,
  unlink: Link2Off,
  openExternal: ExternalLink,
  show: Eye,
  hide: EyeOff,
  refresh: RefreshCw,
  retry: RotateCcw,
  merge: GitMerge,
  replace: Repeat,
  reverse: ArrowLeftRight,
  draw: PenTool,
  measure: Ruler,
  pickArea: SquareDashed,
  scan: Scan,
  zoomIn: ZoomIn,
  zoomOut: ZoomOut,
  navigateTo: Navigation,
  locate: LocateFixed,
  following: Locate,
  compass: Compass,
  northUp: ArrowUp,
  play: Play,
  pause: Pause,
  signOut: LogOut,
  accept: UserCheck,
  ignore: UserX,
  addFriend: UserPlus,
  loading: Loader,
  dragHandle: GripVertical,
  disclosure: ChevronRight,
  expand: ChevronDown,
  collapse: ChevronUp,
  overflow: EllipsisVertical,
  moreTab: Ellipsis,
  success: CircleCheck,
  unselected: Circle,
  warning: TriangleAlert,
  info: Info,
  help: CircleHelp,
  pending: Clock,
  offline: CloudOff,
  sync: Cloud,
  uploading: CloudUpload,
  missingMedia: ImageOff,
  favourite: Star,
  private: Lock,
  map: Map,
  place: MapPin,
  trip: BookOpen,
  saved: Folder,
  route: Route,
  track: Activity,
  waypoint: GitCommit,
  importedFile: FilePlus,
  geoPdf: FileText,
  lidar: Mountain,
  layers: Layers,
  template: LayoutTemplate,
  notes: AlignLeft,
  stats: ChartColumn,
  friends: Users,
  account: CircleUser,
  notifications: Bell,
  settings: Settings,
  email: Mail,
  tag: Tag,
  date: Calendar,
  photo: Image,
  camera: Camera,
  video: Video,
  attachment: Paperclip,
  flag: Flag,
  device: HardDrive,
  phone: Smartphone,
  typography: Type,
  colour: Palette,
  sensors: Cpu,
  elevation: TrendingUp,
  scaleBar: RulerDimensionLine,
} as const satisfies Record<IconIdea, LucideIcon>;

/** A compass NEEDLE, not lucide's Compass: that glyph is a symbol for
 *  "navigation" whose needle points nowhere in particular, while this one
 *  rotates with the map, so its shape is the reading. North is the filled half.
 *  Not an idea: no other surface draws it. */
export const NorthNeedle = createLucideIcon("north-needle", [
  [
    "path",
    { d: "M12 2.5 16.5 12h-9z", className: classes.needleNorth, key: "north" },
  ],
  ["path", { d: "M7.5 12h9L12 21.5z", key: "south" }],
]);
