// Logjam Web's token stylesheet, generated from the shared declarations so the
// browser has no second list of the same values. Pure: it returns the CSS, and
// `frontend/scripts/generate-tokens.mjs` writes it to
// `frontend/src/tokens.generated.css`, which a frontend test holds to this.
import {
  ASSET_HUES,
  CONTROL,
  FONT,
  FONT_WEIGHT,
  MOTION,
  OPACITY,
  PLACE_STATUS_HUES,
  RADIUS,
  SPACE,
} from "./designTokens.js";
import {
  DEFAULT_THEME_SCHEME_ID,
  THEME_SCHEMES,
  THEME_SCHEME_ORDER,
  type ThemeScheme,
} from "./themeSchemes.js";

/** `cardPressed` → `card-pressed`, `geoPdf` → `geo-pdf`, `1.5` → `1-5`. */
export function kebab(name: string): string {
  return name
    .replace(/\./g, "-")
    .replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);
}

const px = (n: number) => `${n}px`;
// Lower case, as the repo's CSS formatter writes hex colours.
const hexCss = (hex: string) => hex.toLowerCase();
const rem = (n: number) => `${n / 16}rem`;

/** The scheme-independent custom properties, in emission order. */
export function webScaleProperties(): [string, string][] {
  return [
    ...Object.entries({ ...ASSET_HUES, ...PLACE_STATUS_HUES }).map(
      ([name, hex]): [string, string] => [`--hue-${kebab(name)}`, hexCss(hex)],
    ),
    // Sorted by size: an object's integer-like keys ("1", "2") enumerate
    // before "0.5" and "1.5" otherwise.
    ...Object.entries(SPACE)
      .sort(([, a], [, b]) => a - b)
      .map(([n, v]): [string, string] => [`--space-${kebab(n)}`, px(v)]),
    ...Object.entries(RADIUS).map(([n, v]): [string, string] => [
      `--radius-${n}`,
      px(v),
    ]),
    ...Object.entries(FONT.web).map(([n, v]): [string, string] => [
      `--font-${n}`,
      rem(v),
    ]),
    ...Object.entries(FONT_WEIGHT).map(([n, v]): [string, string] => [
      `--font-weight-${n}`,
      String(v),
    ]),
    ...Object.entries(CONTROL.web).map(([n, v]): [string, string] => [
      `--control-${n}`,
      px(v),
    ]),
    ...Object.entries(MOTION).map(([n, v]): [string, string] => [
      `--motion-${n}`,
      `${v}ms`,
    ]),
    ...Object.entries(OPACITY).map(([n, v]): [string, string] => [
      `--opacity-${n}`,
      String(v),
    ]),
  ];
}

/** One scheme's custom properties: `color-scheme` plus a `--color-*` per role. */
export function webSchemeProperties(scheme: ThemeScheme): [string, string][] {
  return [
    ["color-scheme", scheme.mode],
    ...Object.entries(scheme.tokens).map(([role, hex]): [string, string] => [
      `--color-${kebab(role)}`,
      hexCss(hex),
    ]),
  ];
}

const block = (selector: string, props: [string, string][]) =>
  `${selector} {\n${props.map(([k, v]) => `  ${k}: ${v};`).join("\n")}\n}\n`;

export function webTokensCss(): string {
  const header =
    "/* GENERATED by `npm run tokens` from @logjam/shared (designTokens.ts,\n" +
    "   themeSchemes.ts). Do not edit: change the declaration and regenerate. */\n";
  const root = block(":root", [
    ...webScaleProperties(),
    ...webSchemeProperties(THEME_SCHEMES[DEFAULT_THEME_SCHEME_ID]),
  ]);
  // A coarse pointer (a finger) gets the touch sizes. Keyed to the POINTER,
  // not the width: a narrow desktop window still has a mouse.
  const coarse =
    "@media (pointer: coarse) {\n" +
    block(
      "  :root",
      Object.entries(CONTROL.touch).map(([n, v]) => [`--control-${n}`, px(v)]),
    )
      .replace(/\n {2}(--)/g, "\n    $1")
      .replace(/\n\}\n$/, "\n  }\n") +
    "}\n";
  const schemes = THEME_SCHEME_ORDER.map((id) =>
    block(`[data-scheme="${id}"]`, webSchemeProperties(THEME_SCHEMES[id])),
  );
  return [header, root, coarse, ...schemes].join("\n");
}
